import os

VIDEO_RESULTS_URL = os.getenv(
    "VIDEO_RESULTS_URL",
    "ws://video-worker:8010/ws/detections",
)
MOONRAKER_URL = os.getenv("MOONRAKER_URL", "")
MOONRAKER_TIMEOUT_SECONDS = float(os.getenv("MOONRAKER_TIMEOUT_SECONDS", "5"))
FAILURE_CONFIDENCE_THRESHOLD = float(
    os.getenv("FAILURE_CONFIDENCE_THRESHOLD", "0.60")
)
FAILURE_CONFIRMATION_MODE = os.getenv("FAILURE_CONFIRMATION_MODE", "frames")
FAILURE_CONFIRMATION_FRAMES = int(os.getenv("FAILURE_CONFIRMATION_FRAMES", "10"))
FAILURE_CONFIRMATION_TIME_SECONDS = float(
    os.getenv("FAILURE_CONFIRMATION_TIME_SECONDS", "5")
)
